version: '3'
services:
  frontend:
    build:
      context: ./Practica2FrontEnd
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  backend:
    build:
      context: ./Practica2BackEnd
      dockerfile: Dockerfile
    ports:
      - 8081:8080
